config/routes.rb
Rails.application.routes.draw do
  get 'ingredient/show'
  devise_for :users
  root 'top#index'
  resources :top, only: [ :show]
  resources :ingredient, only: [ :show,:create] do
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: :show

  namespace 'api' do
    namespace 'v1' do
      get "/search", to: "recipe#search"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient

  validates_uniqueness_of :ingredient_id, scope: :user_id    # バリデーション（ユーザーと食材の組み合わせは一意）
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :categoryId, presence: true
  validates :parentCategoryId, presence: true
  validates :categoryUrl, presence: true

  has_many :favorites
  def full_category
    self.parentCategoryId.to_s + "-" + self.categoryId.to_s
  end

  def favorites_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites

  validates :nickname, presence: true
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < ApplicationController
  def search
    @recipes = RakutenWebService::Recipes::Recipe.search(categoryType: "small")
     render json: { status: 'success', data: @recipes }  
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(ingredient_id: params[:ingredient_id])
    favorite.save
    redirect_to user_path(current_user.id)
  end

  def destroy
    favorite = Favorite.find_by(ingredient_id: params[:ingredient_id], user_id: current_user.id)
    favorite.destroy
    redirect_to user_path(current_user.id)
  end
end

app/controllers/ingredient_controller.rb
class IngredientController < ApplicationController
  before_action :move_to_top, except: [:create, :show]

  def create
    @ingredient=Ingredient.new(ingredient_params)
    if @ingredient.save
      render :show
    else
      ingredient =Ingredient.find_by(name: params[:name])
      redirect_to ingredient_path(ingredient.id)
    end
  end

  def show
    @ingredient=Ingredient.find(params[:id])
  end

  private
    def ingredient_params
        params.permit(:name,:categoryId , :categoryUrl,:parentCategoryId)
    end

    def move_to_top
      unless user_signed_in?
        redirect_to root_path
      end
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
   
  end

  def show
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user

  def show
      @nickname = current_user.nickname

      favorites = Favorite.where(user_id: current_user.id).pluck(:ingredient_id)  # ログイン中のユーザーのお気に入りのingredientカラムを取得
      @favorite_list =Ingredient.find(favorites)
  end

  private

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to root_path
    end
  end
end

app/helpers/api/v1/recipes_helper.rb
module Api::V1::RecipesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredient/show.html.erb
<table border="1" width="500" height="100" class="table">
  <tr>
    <th>食材名</th>
    <th><%= @ingredient.name %></th>
  </tr>
  <tr align="center">
    <td>レシピ一覧へのURL</td>
    <td><%= link_to"こちら", @ingredient.categoryUrl,class:"btn btn--orange" %></td>
  </tr>
  <tr align="center">
    <td>カテゴリーID</td>
    <td><div id ="categoryId"><%= @ingredient.full_category %></div></td>
  </tr>
</table>

<div id="favorite-btn<%= @ingredient.id %>">
  <%if user_signed_in?%>
    <% if  @ingredient.favorites_by?(current_user)%>
      <%=link_to "お気に入り済", ingredient_favorites_path(@ingredient.id),  method: :delete, class:"btn btn-border" %>
    <%  else %>
      <%=link_to "お気に入り登録", ingredient_favorites_path(@ingredient.id), method: :post, class:"btn btn-border" %>
    <% end %>
  <%else%>
    お気に入り登録機能を使用する場合はログインをしてください。
  <%end%>
</div>

<div>
<h1>おすすめのレシピ４選</h1>
</div>
<ul id="recipe_ranking_list" class="ranking_ul"></ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodayRecipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  <%= render "top/header"%>
    <%= yield %>
  </body>
  <%= render "top/footer"%>
</html>

app/views/top/_footer.html.erb
<div class="top-footer">
  <div class="footer-main">
    <!-- Rakuten Web Services Attribution Snippet FROM HERE -->
    <a href="https://developers.rakuten.com/" target="_blank">Supported by Rakuten Developers</a>
    <!-- Rakuten Web Services Attribution Snippet TO HERE -->
  </div>
</div>

app/views/top/_header.html.erb
<div class="top-header">
  <div class ="top-header-title">
  <%= link_to "今日のご飯どうする？", root_path  ,class: "nav-link"%>
  </div>
  <% if user_signed_in? %>
    <div class="user_nav">
      <%= link_to "マイページ", "/users/#{current_user.id}" , class: "nav-link"%>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "nav-link"%>
      <div class="top-header-username">
        <%=current_user.nickname %>さん
      </div>
    </div>
  <% else %>
    <div class="user_nav">
      <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
      <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
    </div>
  <% end %>
</div>

app/views/top/index.html.erb
<div class="main-index-guidance">
  食材名を入力してください<br>
  <input type="text" id="search-text" class="search__word">
</div>
<div class="main-index-api">
  <ul id="recipe_list" class="recipi_index_list"></ul>
</div>

app/views/users/show.html.erb
<div class="user-index">
  <h1>こんにちは<%= @nickname %>さん</h1>
  <div class="contents">
    <h2><%= @nickname %>さんのお気に入り食材一覧</h2>
    <div class="favorites-li">
      <% if @favorite_list.present? %>
        <% @favorite_list.each do |item| %>
          <div class="favorites-show">
            <div class="favorites">
              <%= link_to item.name,ingredient_path(item.id) ,class: "nav-link" %>
            </div>
            <%= link_to "お気に入り解除", ingredient_favorites_path(item.id),  method: :delete, class: "favorite-de" %>
            </div>
        <% end %>
      <% else%>
      お気に入り食材は登録されていません。各食材ページから登録してください。
      <% end %>
    </div>
  </div>
</div>